#!/usr/bin/env node
var browserify = require('browserify')
  , path       = require('path')
  , fs         = require('fs')

var files = {
  output: fs.createWriteStream('slack.js'),
  testing: fs.createWriteStream('slack-testing.js')
}

browserify('.', {standalone:'slack'})
  .ignore('/src/_exec-electron.js')
  .transform('envify', {
    'NODE_ENV': 'production',
    'STENO_URL': false
  })
  .bundle()
  .pipe(files.output)

browserify('.', {standalone:'slack'})
  .ignore('/src/_exec-electron.js')
  .transform('envify', {
    'NODE_ENV': 'testing',
    'STENO_URL': false
  })
  .bundle()
  .pipe(files.testing)
