#!/usr/bin/env node
const request = require('request')

const url = 'https://api.slack.com/specs/openapi/v2/slack_web.json'

function generateJSON(api) {
  let json = {}

  Object.entries(api.paths).forEach(([path, operations]) => {
    const methodName = path.substr(1, path.length - 1)
    const properties = operations.get || operations.post

    json[methodName] = properties.parameters
      .filter(param => param.required)
      .map(param => param.name)
  })

  console.log(JSON.stringify(json, null, 2))
}

function getAPI() {
  request(url, (err, res) => {
    generateJSON(JSON.parse(res.body))
  })
}

getAPI()
