#!/usr/bin/env node
var fs = require('fs')
var cheerio = require('cheerio')
var mustache = require('mustache')
var execSync = require('child_process').execSync

var exec = function (cmd) {
  return execSync(cmd, {stdio:[0,1,2]})
}

var generateReadme = function (data) {
  var rendered = mustache.render(fs.readFileSync(__dirname + '/../readme.tmpl', { encoding: 'utf8'}), data)
  fs.writeFileSync(__dirname + '/../readme.md', rendered)
  console.log("🙌  Generated readme.md")
}

exec(__dirname + '/generate-api-json > ' + __dirname + '/../src/api.json')
console.log("⚡️  Updated src/api.json")

// generate README docs
var api = require('../src/api.json')
var methods = []
Object.keys(api).sort().forEach(method=> {
  var isRequired = param=> param.required === 'Required'
  var params = api[method].filter(isRequired).map(param=> param.name).join(', ')
  var interpolated = `slack.${method}({${params}}, (err, data) => { })`
  methods.push(interpolated)
})

generateReadme({methods})
