#!/usr/bin/env node
Slack = require('../')

// omg no var, let or const?! u monster
path = require('path')
repl = require('repl')
chalk = require('chalk')
env = require('node-env-file')

// read secrets and interpolate with process.env
env(path.join(process.cwd(), '.env'))

// setup the repl
prompt = chalk.green('#!/slack> ')
server = repl.start({prompt})

// adds some predefined variables
server.context.slack = Slack
server.context.bot = new Slack({token: process.env.SLACK_BOT_TOKEN})
