#!/usr/bin/env node
var req = require('request')
var url = 'https://api.slack.com/rtm'
var cheerio = require('cheerio')

req(url, (err, res)=> {
 
  var methods = []
  var $ = cheerio.load(res.body)
  
  $('table a').each(function(i, elem) {
    methods[i] = $(this).text()
  })

  console.log(methods)
})

